# Generated by Django 4.2.28 on 2026-02-24 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.labtest'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='visits.visit'),
        ),
    ]
